Estudiando: https://arxiv.org/pdf/2209.15421.pdf

In [1]:
import pandas as pd
from sklearn.preprocessing import quantile_transform

## Categorical
our model takes one-hot encoded versions of categorical features as an input

In [22]:
df = pd.read_csv('../../../datasets/kingcounty/raw/kc_house_data.csv')
category_columns=("condition", "floors", "grade", "view", "waterfront", "zipcode", "bathrooms", "bedrooms",)
continues_columns=('price', 'sqft_living', 'sqft_lot', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long',
       'sqft_living15', 'sqft_lot15',)

In [3]:
df.loc[:, category_columns]

condition  floors  grade  view  waterfront  zipcode  bathrooms  \
0              3     1.0      7     0           0    98178       1.00   
1              3     2.0      7     0           0    98125       2.25   
2              3     1.0      6     0           0    98028       1.00   
3              5     1.0      7     0           0    98136       3.00   
4              3     1.0      8     0           0    98074       2.00   
...          ...     ...    ...   ...         ...      ...        ...   
21608          3     3.0      8     0           0    98103       2.50   
21609          3     2.0      8     0           0    98146       2.50   
21610          3     2.0      7     0           0    98144       0.75   
21611          3     2.0      8     0           0    98027       2.50   
21612          3     2.0      7     0           0    98144       0.75   

       bedrooms  
0             3  
1             3  
2             2  
3             4  
4             3  
...         ...  
21608         3  
21609         4  
21610         2  
21611         3  
21612         2  

[21613 rows x 8 columns]

In [41]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(df.loc[:, category_columns])
display(enc.categories_)
category_data = enc.transform(df.loc[:, category_columns]).toarray()
display(category_data.shape)

[array([1, 2, 3, 4, 5]),
 array([1. , 1.5, 2. , 2.5, 3. , 3.5]),
 array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 array([0, 1, 2, 3, 4]),
 array([0, 1]),
 array([98001, 98002, 98003, 98004, 98005, 98006, 98007, 98008, 98010,
        98011, 98014, 98019, 98022, 98023, 98024, 98027, 98028, 98029,
        98030, 98031, 98032, 98033, 98034, 98038, 98039, 98040, 98042,
        98045, 98052, 98053, 98055, 98056, 98058, 98059, 98065, 98070,
        98072, 98074, 98075, 98077, 98092, 98102, 98103, 98105, 98106,
        98107, 98108, 98109, 98112, 98115, 98116, 98117, 98118, 98119,
        98122, 98125, 98126, 98133, 98136, 98144, 98146, 98148, 98155,
        98166, 98168, 98177, 98178, 98188, 98198, 98199]),
 array([0.  , 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75,
        3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 ,
        5.75, 6.  , 6.25, 6.5 , 6.75, 7.5 , 7.75, 8.  ]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 33])]

(21613, 143)

In [42]:
display(category_data[0])
display(df.loc[:, category_columns].iloc[0])

array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

condition         3.0
floors            1.0
grade             7.0
view              0.0
waterfront        0.0
zipcode       98178.0
bathrooms         1.0
bedrooms          3.0
Name: 0, dtype: float64

## Numerical Features
normalized numerical features, we use the gaussian quantile transformation from the scikit-learn library 

In [43]:
import numpy as np
import numpy as np
from sklearn.preprocessing import QuantileTransformer
qt = QuantileTransformer(n_quantiles=10, random_state=0)
continues_data = qt.fit_transform(df.loc[:, continues_columns])


In [44]:
display(continues_data[0])
display(df.loc[:, continues_columns].iloc[0])

array([0.09326984, 0.13777778, 0.29763362, 0.24444444, 0.        ,
       0.28888889, 0.        , 0.32850242, 0.46932007, 0.1503268 ,
       0.29444444])

price            221900.0000
sqft_living        1180.0000
sqft_lot           5650.0000
sqft_above         1180.0000
sqft_basement         0.0000
yr_built           1955.0000
yr_renovated          0.0000
lat                  47.5112
long               -122.2570
sqft_living15      1340.0000
sqft_lot15         5650.0000
Name: 0, dtype: float64

In [58]:
x_in = pd.concat([pd.DataFrame(continues_data, columns=qt.get_feature_names_out()), pd.DataFrame(category_data, columns=enc.get_feature_names_out())], axis=1)

In [59]:
x_in

price  sqft_living  sqft_lot  sqft_above  sqft_basement  yr_built  \
0      0.093270     0.137778  0.297634    0.244444       0.000000  0.288889   
1      0.629167     0.752381  0.449630    0.733918       0.692593  0.244444   
2      0.066667     0.064257  0.697278    0.076190       0.000000  0.141414   
3      0.706061     0.518519  0.231334    0.152778       0.881481  0.407407   
4      0.590278     0.383838  0.553086    0.559671       0.000000  0.644444   
...         ...          ...       ...         ...            ...       ...   
21608  0.333333     0.306878  0.022042    0.477778       0.000000  0.925926   
21609  0.404030     0.669841  0.314259    0.774854       0.000000  0.987654   
21610  0.407743     0.097724  0.029942    0.131944       0.000000  0.925926   
21611  0.404030     0.343434  0.067388    0.516667       0.000000  0.857143   
21612  0.258547     0.097724  0.020058    0.131944       0.000000  0.913580   

       yr_renovated       lat      long  sqft_living15  ...  bedrooms_3  \
0          0.000000  0.328502  0.469320       0.150327  ...         1.0   
1          0.998677  0.881636  0.283951       0.398693  ...         1.0   
2          0.000000  0.918464  0.509121       0.850129  ...         0.0   
3          0.000000  0.352657  0.093333       0.163399  ...         0.0   
4          0.000000  0.601242  0.865359       0.469136  ...         1.0   
...             ...       ...       ...            ...  ...         ...   
21608      0.000000  0.818683  0.196296       0.285714  ...         1.0   
21609      0.000000  0.327640  0.137037       0.487654  ...         0.0   
21610      0.000000  0.550915  0.347670       0.078320  ...         0.0   
21611      0.000000  0.391589  0.833987       0.196078  ...         1.0   
21612      0.000000  0.550142  0.347670       0.078320  ...         0.0   

       bedrooms_4  bedrooms_5  bedrooms_6  bedrooms_7  bedrooms_8  bedrooms_9  \
0             0.0         0.0         0.0         0.0         0.0         0.0   
1             0.0         0.0         0.0         0.0         0.0         0.0   
2             0.0         0.0         0.0         0.0         0.0         0.0   
3             1.0         0.0         0.0         0.0         0.0         0.0   
4             0.0         0.0         0.0         0.0         0.0         0.0   
...           ...         ...         ...         ...         ...         ...   
21608         0.0         0.0         0.0         0.0         0.0         0.0   
21609         1.0         0.0         0.0         0.0         0.0         0.0   
21610         0.0         0.0         0.0         0.0         0.0         0.0   
21611         0.0         0.0         0.0         0.0         0.0         0.0   
21612         0.0         0.0         0.0         0.0         0.0         0.0   

       bedrooms_10  bedrooms_11  bedrooms_33  
0              0.0          0.0          0.0  
1              0.0          0.0          0.0  
2              0.0          0.0          0.0  
3              0.0          0.0          0.0  
4              0.0          0.0          0.0  
...            ...          ...          ...  
21608          0.0          0.0          0.0  
21609          0.0          0.0          0.0  
21610          0.0          0.0          0.0  
21611          0.0          0.0          0.0  
21612          0.0          0.0          0.0  

[21613 rows x 154 columns]

## Forward diffusion process
Each categorical feature is handled by a separate forward diffusion process
